### ISSUE TITLE
possible error in p_gamma_scale and p_gamma_rate

### ISSUE THREAD

**Issue by giadasp** [jwindle/BayesLogit#7]
Dear Jesse,
I was looking at the cpp code of the package BayesLogit and I've noticed that the two macros `p_gamma_scale` and `p_gamma_rate` may call the wrong R functions.
File "simple_RNG_wrapper.h", lines 43, 44 say:
```
#define p_gamma_scale(X, SHAPE, SCALE, USE_LOG) pgamma((X), (SHAPE), (SCALE), 1, (USE_LOG))
#define p_gamma_rate(X, SHAPE, RATE, USE_LOG) pgamma((X), (SHAPE), (1./(RATE)), 1, (USE_LOG))
```
But `pgamma` function in R actually has the following signature (rate comes before scale):
`pgamma(q, shape, rate = 1, scale = 1/rate, lower.tail = TRUE, log.p = FALSE)`

This means that maybe the macros are swapped.
Let me know if it is correct.
Thank you

Giada

**Comment by giadasp** [comment]
Inoticed that this macro (same file, line 48) has the same problem: 

`#define expon_rate(RATE) rexp((1./(RATE)))`

since rexp takes the rate as parameter.

**Comment by coatless** [comment]
@giadasp great questions! Glancing through, @jwindle may have made a mistake with the `pgamma` variant.

For the `pgamma()` function in _R_, we have: 

https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/src/simple_RNG_wrapper.h#L43-L44

Inside of the R function, we have:

```cpp
pgamma <- function(q, shape, rate = 1, scale = 1/rate,
                   lower.tail = TRUE, log.p = FALSE)
{
    if(!missing(rate) && !missing(scale)) {
        if(abs(rate*scale - 1) < 1e-15)
            warning("specify 'rate' or 'scale' but not both")
        else
            stop("specify 'rate' or 'scale' but not both")
    }
    .Call(C_pgamma, q, shape, scale, lower.tail, log.p)
}
```
https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/library/stats/R/distn.R#L65-L75

So, there should be a swap.

----

On the other note, I'm not sure the use of the `rexp()` macro is incorrect given:

https://github.com/jwindle/BayesLogit/blob/24669046e8dfec9128c65fff9b916473dd505c9a/src/simple_RNG_wrapper.h#L47-L48

Matches the implementation in the _R_ function as:

```r
rexp <- function(n, rate=1) .Call(C_rexp, n, 1/rate)
```
https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/library/stats/R/distn.R#L25

**Comment by jwindle** [comment]
Just wondering, have you all looked at Rmath, e.g.

https://github.com/statslabs/rmath/blob/master/src/rgamma.c

**Comment by coatless** [comment]
@jwindle I think you mean `pgamma`? Not `rgamma`? 

That function definition matches the above use from R?

```cpp
double pgamma(double x, double alph, double scale, int lower_tail, int log_p)
```

https://github.com/wch/r-source/blob/d8258ffd68db46b4269f4982b408dede365fe701/src/nmath/pgamma.c#L721

**Comment by jwindle** [comment]
I think I'm maybe missing something

```
#define p_gamma_scale(X, SHAPE, SCALE, USE_LOG) pgamma((X), (SHAPE), (SCALE), 1, (USE_LOG)) 
double pgamma(double x, double alph, double scale, int lower_tail, int log_p)
C_pgamma(double q, double shape, double scale, int lower_tail, int log_p) // it seems
```
Where are the parameters getting scrambled?

**Comment by giadasp** [comment]
Thank you @coeatless and @jwindle for the attention. 
I think it's my fault. I didn't understood that the definitions are calling the C functions `C_pgamma `and `C_rexp`. I thought they called the R wrappers of the functions `pgamma` and `rexp` as the names suggest.
In that case I think everything is fine. Sorry for opening the issue. I can close it.
